services:
    go:
        container_name: go
        build:
            context: .
            dockerfile: ./.docker/go/Dockerfile
        volumes:
            - ./src:/var/www/html
            - /var/www/html/frontend
        ports:
            - "8888:8888"
        networks:
            - main_network
        depends_on:
            - mongodb

    svelte:
        container_name: svelte
        build:
            context: .
            dockerfile: ./.docker/svelte/Dockerfile
        volumes:
            - ./src/frontend/:/var/www/html
            - /var/www/html/node_modules
        networks:
            - main_network
        depends_on:
            - mongodb

    mongodb:
        container_name: mongodb
        image: mongodb/mongodb-community-server:7.0.9-ubi9
        networks:
            - main_network
        volumes:
            - 'mongodb:/data/db'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass

networks:
    main_network:
        driver: bridge

volumes:
    mongodb:
        driver: local
